-- MySQL Script generated by MySQL Workbench
-- 09/01/15 16:22:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema daoh_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema daoh_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daoh_test` DEFAULT CHARACTER SET utf8 ;
USE `daoh_test` ;

-- -----------------------------------------------------
-- Table `daoh_test`.`user_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`user_detail` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `cellphone` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daoh_test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`user` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `user_detail_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_user_detail1_idx` (`user_detail_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_user_detail1`
    FOREIGN KEY (`user_detail_id`)
    REFERENCES `daoh_test`.`user_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daoh_test`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`news` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '',
  `topic` VARCHAR(45) NULL COMMENT '',
  `publication_date` DATETIME NULL COMMENT '',
  `news_text` LONGTEXT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_news_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `daoh_test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daoh_test`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`role` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '',
  `role_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daoh_test`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`tag` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '',
  `tag_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daoh_test`.`news_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`news_tag` (
  `news_id` INT NOT NULL COMMENT '',
  `tag_id` INT NOT NULL COMMENT '',
  INDEX `fk_news_has_tag_tag1_idx` (`tag_id` ASC)  COMMENT '',
  INDEX `fk_news_has_tag_news1_idx` (`news_id` ASC)  COMMENT '',
  CONSTRAINT `fk_news_has_tag_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `daoh_test`.`news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `daoh_test`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daoh_test`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daoh_test`.`user_role` (
  `role_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  INDEX `fk_role_has_user_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_role_has_user_role1_idx` (`role_id` ASC)  COMMENT '',
  CONSTRAINT `fk_role_has_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `daoh_test`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `daoh_test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
